# Generated by Django 2.1.1 on 2018-12-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181207_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(related_name='users_set', to='rbac.Role', verbose_name='角色'),
        ),
    ]
