# Generated by Django 2.1.1 on 2018-12-07 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workbench.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able', models.BooleanField(default=True, verbose_name='是否启用')),
                ('file', models.FileField(blank=True, null=True, upload_to=workbench.models.get_file_path, verbose_name='附件')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able', models.BooleanField(default=True, verbose_name='是否启用')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='消息内容')),
                ('state', models.CharField(choices=[('1', '未确认'), ('2', '已确认'), ('3', '推迟')], default='1', max_length=4, verbose_name='消息状态')),
                ('pub_time', models.DateTimeField(verbose_name='出现时间')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('received_describe', models.CharField(blank=True, max_length=256, null=True, verbose_name='确认描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('state', models.CharField(choices=[('1', '进行中'), ('2', '挂起'), ('3', '已完成')], default='2', max_length=10, verbose_name='计划状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='计划描述')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='预计完成日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img_url', models.URLField(null=True, verbose_name='图片URL')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_plan', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.Plan', verbose_name='父计划')),
            ],
            options={
                'verbose_name': '工作计划',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.PlanType', verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='plan',
            name='related_user',
            field=models.ManyToManyField(blank=True, related_name='related_plan', to=settings.AUTH_USER_MODEL, verbose_name='相关人员'),
        ),
        migrations.AddField(
            model_name='message',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.Plan', verbose_name='相关plan'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.Plan', verbose_name='所属plan'),
        ),
    ]
