# Generated by Django 2.1.1 on 2018-12-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_able',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_able',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
